# Generated by Django 3.0.2 on 2020-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gems', models.TextField(default='')),
                ('spent_money', models.IntegerField(default=0)),
            ],
        ),
    ]
