# Generated by Django 3.0.2 on 2020-04-28 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('spent_money', models.DecimalField(decimal_places=0, default=0, max_digits=9, validators=[django.core.validators.DecimalValidator(decimal_places=0, max_digits=9)])),
            ],
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customers', models.ManyToManyField(related_name='gems', to='top_customers.Customer')),
            ],
        ),
    ]
